services:
  pico-limbo:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        BINARY_NAME: pico_limbo
    image: ghcr.io/quozul/picolimbo:latest
    ports:
      - "30066:25565"
